// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: pb/v1/transaction_service.proto

package transactionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransferServiceClient is the client API for TransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransferServiceClient interface {
	CreditUser(ctx context.Context, in *CreditUserRequest, opts ...grpc.CallOption) (*CreditUserResponse, error)
	DebitUser(ctx context.Context, in *DebitUserRequest, opts ...grpc.CallOption) (*DebitUserResponse, error)
}

type transferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransferServiceClient(cc grpc.ClientConnInterface) TransferServiceClient {
	return &transferServiceClient{cc}
}

func (c *transferServiceClient) CreditUser(ctx context.Context, in *CreditUserRequest, opts ...grpc.CallOption) (*CreditUserResponse, error) {
	out := new(CreditUserResponse)
	err := c.cc.Invoke(ctx, "/transaction.v1.TransferService/CreditUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) DebitUser(ctx context.Context, in *DebitUserRequest, opts ...grpc.CallOption) (*DebitUserResponse, error) {
	out := new(DebitUserResponse)
	err := c.cc.Invoke(ctx, "/transaction.v1.TransferService/DebitUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferServiceServer is the server API for TransferService service.
// All implementations should embed UnimplementedTransferServiceServer
// for forward compatibility
type TransferServiceServer interface {
	CreditUser(context.Context, *CreditUserRequest) (*CreditUserResponse, error)
	DebitUser(context.Context, *DebitUserRequest) (*DebitUserResponse, error)
}

// UnimplementedTransferServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTransferServiceServer struct {
}

func (UnimplementedTransferServiceServer) CreditUser(context.Context, *CreditUserRequest) (*CreditUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreditUser not implemented")
}
func (UnimplementedTransferServiceServer) DebitUser(context.Context, *DebitUserRequest) (*DebitUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DebitUser not implemented")
}

// UnsafeTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransferServiceServer will
// result in compilation errors.
type UnsafeTransferServiceServer interface {
	mustEmbedUnimplementedTransferServiceServer()
}

func RegisterTransferServiceServer(s grpc.ServiceRegistrar, srv TransferServiceServer) {
	s.RegisterService(&TransferService_ServiceDesc, srv)
}

func _TransferService_CreditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).CreditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.v1.TransferService/CreditUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).CreditUser(ctx, req.(*CreditUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_DebitUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebitUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).DebitUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.v1.TransferService/DebitUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).DebitUser(ctx, req.(*DebitUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransferService_ServiceDesc is the grpc.ServiceDesc for TransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.v1.TransferService",
	HandlerType: (*TransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreditUser",
			Handler:    _TransferService_CreditUser_Handler,
		},
		{
			MethodName: "DebitUser",
			Handler:    _TransferService_DebitUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/v1/transaction_service.proto",
}
